live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 19

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 7

[font.italic]
style = "Italic"

[font.normal]
family = "DankMono Nerd Font Mono"

[font.offset]
x = 0
y = 14

[scrolling]
history = 50000

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 7
